"""main_models

Revision ID: 272d0bbf8f1d
Revises: 36dcf6fa3d85
Create Date: 2023-08-11 10:03:26.417083

"""


# revision identifiers, used by Alembic.
revision = "272d0bbf8f1d"
down_revision = "36dcf6fa3d85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
